flashcardQuestions = {
    "1": "What is the difference between the = and ==  operators in Python?",
    "2": "What is the purpose of the 'while' loop in Python?",
    "3": "How do you define a function in Python?",
    "4": "What is the purpose of the 'for' loop in Python?",
    "5": "What is the result of 'a' + 'b' * 2?",
    "6": "How do you get the last element from a list named my_list?",
    "7": "What is the purpose of the len() function in Python?",
    "8": "What function is used to get input from the user in the Python console?",
    "9": "What will bool(0) evaluate to?",
    "10": "How do you add an element 5 to the end of a list named my_list?",
    "11": "What is the output of print(float(4))?",
    "12": "What does the modulo operator do in Python?",
    "13": "Which keyword is used to stop a loop and continue with the next statement in a loop?",
    "14": "What is a variable's scope in Python?",
    "15": "How do you access the character 'c' in the string s = 'abcde'?",
    "16": "What is the purpose of an if-else statement in Python?",
    "17": "What is the output of list(range(5))?",
    "18": "Which keyword is used to bring a module into a program?",
    "19": "What is the purpose of the return statement in Python?",
    "20": "How do you handle potential errors in a block of code?"
}

flashcardAnswers = {
    "1": "The = operator assigns a value to a variable, while the == operator compares two values.",
    "2": "The while loop is used to repeat a block of code as long as a condition is true.",
    "3": "A function in Python is defined using the def keyword followed by the function name and parentheses.",
    "4": "The for loop is used to iterate over a sequence (such as a list or string) and perform a block of code for each element.",
    "5": "'abab'",
    "6": "You can access the last element of a list using the index -1.",
    "7": "The len() function returns the number of items in an object.",
    "8": "The input() function is used to get input from the user in the Python console.",
    "9": "bool(0) evaluates to False.",
    "10": "You can add an element 5 to the end of a list using the append() method.",
    "11": "The output of print(float(4)) is 4.0.",
    "12": "The modulo operator (%) returns the remainder of a division operation.",
    "13": "The continue keyword is used to skip the current iteration of a loop and continue with the next iteration.",
    "14": "A variable's scope in Python refers to the visibility of a variable within a program.",
    "15": "The character 'c' in the string s = 'abcde' can be accessed using s[2].",
    "16": "The if-else statement is used to perform different actions based on a condition.",
    "17": "The output of list(range(5)) is [0, 1, 2, 3, 4].",
    "18": "The import keyword is used to bring a module into a program.",
    "19": "The return statement is used to return a value from a function.",
    "20": "You can handle potential errors in a block of code using try-except statements."
}