flashcardQuestions = {
    "1": "What is a language?",
    "2": "What is a natural language?",
    "3": "What is a programming language?",
    "4": "What is a high-level programming language?",
    "5": "What is a machine language?",
    "6": "What is an instruction list?",
    "7": "What is source code?",
    "8": "What constitutes a language?",
    "9": "How can source code be translated?",
    "10": "Can source code be directly executed by a computer?",
    "11": "What kind of language is Python?",
    "12": "What is a literal?",
    "13": "What is an integer?",
    "14": "What is a float?",
    "15": "What is a string literal?",
    "16": "What is a Boolean literal?",
    "17": "What is a None literal?",
    "18": "What is an operator?",
    "19": "What is a unary operator?",
    "20": "What is a binary operator?"
}

flashcardAnswers = {
    "1": "A means (and a tool) for expressing and recording thoughts",
    "2": "A language people use to communicate with each other in everyday life",
    "3": "A language developed by humans and used to communicate with computers",
    "4": "A programming language which operates on a high level of abstraction",
    "5": "A language placed at the lowest level of computer programming",
    "6": "A list of all elementary (atomic) operations which can be executed by a certain CPU",
    "7": "A text encoded in any of the programming languages (regardless of the language's level)",
    "8": "An alphabet, a lexis, syntax, and semantics",
    "9": "Interpretation or compilation",
    "10": "No",
    "11": "An interpreted programming language",
    "12": "Data whose value is determined by the literal itself",
    "13": "A type dedicated to storing integral numbers",
    "14": "A type designed to store real numbers",
    "15": "Sequences (including empty ones) of characters (digits, letters, punctuation marks, etc.)",
    "16": "The only two possible values used by the Boolean algebra (True and False)",
    "17": "A literal that denotes an empty value",
    "18": "A symbol that determines an operation to perform",
    "19": "An operator with one operand",
    "20": "An operator with two operands"
}
