flashcardQuestions = {
    "1": "What is the difference between the = and ==  operators in Python?",
    "2": "What is the purpose of the 'while' loop in Python?",
    "3": "How do you define a function in Python?",
    "4": "What is the purpose of the 'for' loop in Python?",
    "5": "What is the result of 'a' + 'b' * 2?",
    "6": "How do you get the last element from a list named my_list?",
    "7": "What is the purpose of the len() function in Python?",
    "8": "What function is used to get input from the user in the Python console?",
    "9": "What will bool(0) evaluate to?",
    "10": "How do you add an element 5 to the end of a list named my_list?",
    "11": "What is the output of print(float(4))?",
    "12": "What does the modulo operator do in Python?",
    "13": "Which keyword is used to stop a loop and continue with the next statement in a loop?",
    "14": "What is a variable's scope in Python?",
    "15": "How do you access the character 'c' in the string s = 'abcde'?",
    "16": "What is the purpose of an if-else statement in Python?",
    "17": "What is the output of list(range(5))?",
    "18": "Which keyword is used to bring a module into a program?",
    "19": "What is the purpose of the return statement in Python?",
    "20": "How do you handle potential errors in a block of code?"
}

flashcardAnswers = {
    "1": "",
    "2": "",
    "3": "",
    "4": "",
    "5": "",
    "6": "",
    "7": "",
    "8": "",
    "9": "",
    "10": "",
    "11": "",
    "12": "",
    "13": "",
    "14": "",
    "15": "",
    "16": "",
    "17": "",
    "18": "",
    "19": "",
    "20": ""
}